apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ci-pipeline
spec:
  tasks:
    - name: ci
      taskRef:
        name: ci
---
apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: ci-template
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: ci-
      spec:
        pipelineRef:
          name: ci-pipeline
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: binding-ci-github-pr
spec:
  params:
    - name: repository
      value: "$(event.pull_request.base.repo.clone_url)"
    - name: branch
      value: "$(event.pull_request.base.ref)"
    - name: revision
      value: "$(event.pull_request.head.sha)"
    - name: triggerName
      value: "github-pullrequest"
    - name: prnum
      value: "$(event.number)"
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: ci-git-pr
spec:
  triggers:
    - binding:
        name: binding-ci-github-pr
      template:
        name: ci-template
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: ci
spec:
  steps:
    - name: git-sync
      image: ibmcom/pipeline-base-image:2.6
      command:
        - bash
      args:
        - -cxe
        - | 
          echo hello world
          
          cat <<EOF > /workspace/output/pr/status/tekton.json
          {
            "ID": "tekton",
            "Code": "success",
            "Description": "Tekton is running"
          }
          EOF
