apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ci-pipeline
spec:
  params:
    - name: revision
  tasks:
    - name: ci
      taskRef:
        name: ci
      params:
        - name: revision
          value: $(params.revision)
---
apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: ci-template
spec:
  params:
    - name: revision
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: ci-
      spec:
        params:
        - name: revision
          value: $(params.revision)
        pipelineRef:
          name: ci-pipeline
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: binding
spec:
  params:
    - name: repository
      value: "https://github.com/ajgarozz/tekton"
    - name: revision
      value: "$(event.ref)" # /refs/head/<branch>
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: binding-ci-github-pr
spec:
  params:
    - name: repository
      value: "$(event.pull_request.base.repo.clone_url)"
    - name: branch
      value: "$(event.pull_request.base.ref)"
    - name: revision
      value: "$(event.pull_request.head.sha)"
    - name: triggerName
      value: "github-pullrequest"
    - name: prnum
      value: "$(event.number)"
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: ci-git-pr
spec:
  triggers:
    - binding:
        name: binding-ci-github-pr
      template:
        name: ci-template
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: ci
spec:
  triggers:
    - binding:
        name: binding
      template:
        name: ci-template
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: ci
spec:
  params:
    - name: revision
  steps:
    - name: git-sync
      image: ibmcom/pipeline-base-image:2.6
      command:
        - bash
      args:
        - -cxe
        - | 
          echo hello world
